# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ekuseru"
  s.version = "0.3.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nugroho Herucahyono", "Jacob Rothstein"]
  s.date = "2011-11-21"
  s.description = "Ekuseru is a gem to generate Microsoft Excel documents with Rails. This plugin provides templating abilities to create excel documents using Spreadsheet gem."
  s.email = "xinuc@xinuc.org"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ekuseru.gemspec",
    "install.rb",
    "lib/ekuseru.rb",
    "lib/template_handler/eku.rb",
    "lib/template_handler/options.rb",
    "test/ekuseru_controller_test.rb",
    "test/fixtures/ekuseru/index.xls.eku",
    "test/test.log",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/xinuc/ekuseru"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Export excel documents from Rails"

  s.add_dependency('rails', ">= 3.0")
  s.add_dependency('spreadsheet', ">= 0.6")
  s.add_development_dependency 'jeweler'
end
